# Introduccción {#intro}

El presente manual, orientado al proceso de fortalecimiento de las capacidades en el manejo de softwares especializados para la gestión de datos en el contexto de las entidades públicas, presenta las generalidades, los procesos de instalación, la forma de navegación y el flujo de trabajo de tres de los principales softwares, de naturaleza comercial, orientados a las gestión de datos de naturaleza cuantitativa: Tableau, PowerBI y Flourish.

Este trabajo hace parte de los esfuerzos realizados por la [Oficina Nacional de Estadística](http://estadisticas.unal.edu.co/home/) de la [Universidad Nacional de Colombia](https://unal.edu.co/) con el fin de fortalecer las competencias en las herramientas existentes para la gestión de datos y, por su intermedio, mejorar los procesos de producción y uso de información cuantitativa en las demás universidades públicas del país, así como en entidades u organismos interesados en este recurso -los datos- cada vez más útil para la gestión contemporanea. 

